# Generated by Django 4.0.4 on 2022-06-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_details',
            name='Phone_Number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
